arcface: True
arch:
  _target_: model.ASLLinearModel
  in_features: ${dataset.in_features}
  first_out_features: 2048
  num_classes: 250
  num_blocks: 3
  drop_rate: 0.4

loss:
  _target_: loss.SoftmaxLoss
  in_features: 256
  out_features: 250